export enum StockMovementType {
  ENTRADA = 'ENTRADA',
  SAIDA = 'SAIDA',
  AJUSTE = 'AJUSTE',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DEVOLUCAO = 'DEVOLUCAO',
  INVENTARIO = 'INVENTARIO',
}

export enum RecommendationType {
  LOW_STOCK = 'LOW_STOCK',
  STOCKOUT_RISK = 'STOCKOUT_RISK',
  SLOW_MOVING = 'SLOW_MOVING',
  OVERSTOCK = 'OVERSTOCK',
  PURCHASE_RECOMMENDATION = 'PURCHASE_RECOMMENDATION',
  SALES_ANOMALY = 'SALES_ANOMALY',
  MARGIN_ALERT = 'MARGIN_ALERT',
  PROMOTION_OPPORTUNITY = 'PROMOTION_OPPORTUNITY',
}

export enum RecommendationStatus {
  PENDING = 'PENDING',
  VIEWED = 'VIEWED',
  APPROVED = 'APPROVED',
  DISMISSED = 'DISMISSED',
  EXECUTED = 'EXECUTED',
}

export enum SaleStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}
